[package]
name = "advent_23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
regex = "1.10.2"
